name: ames-training-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn
      - joblib
      - pyarrow
      - azureml-mlflow
      - mlflow